language: objective-c
osx_image: xcode9
xcode_workspace: demo/AgoraVRTCDemo.xcworkspace
xcode_scheme: KMCAgoraVRTCDemo
script:
    - xcodebuild clean build -sdk iphonesimulator -workspace demo/AgoraVRTCDemo.xcworkspace -scheme KMCAgoraVRTCDemo CODE_SIGNING_REQUIRED=NO