
project 'KMCAgoraVRTCDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'KMCAgoraVRTCDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AgoraVRTCDemo
  pod 'MBProgressHUD'
  pod 'libksygpulive/KSYGPUResource'
  pod 'libksygpulive/libksygpulive'
  pod 'UICKeyChainStore', '~> 2.1.1'
  pod 'AgoraRtcEngine_iOS', '1.14.0'
end

